### ISSUE TITLE
Cannot switch to DISARM, pulse PGM not working

### ISSUE THREAD

**Issue by HajLender** [e-mcgee/paradox_platform#10]
I struggled to config this plugin but it finally works, however I have 2 problems I cannot solve:

1. I am able to ARM the alarm, put to SLEEP and STAY. However I am not able to keep the alarm on DISARM status, it just switches itself after couple seconds to STAY

2. I have a garage door connected to PGM1 that works on pulse signal (one click open, another click stop another click close, and again). I am able to control it via the iphone app (however not in pulse mode, need to click the off button manually everytime) and the REM2 remote as well, but I am not able to make it work with this plugin at all. 
EDIT: the garage door is connected to the Paradox 5050 panel, not directly to IP150

Is it possible to disable continual request from the alarm regarding the zones (I don't need it) so it refreshes the status less often?

Thank you for any help

David

**Comment by e-mcgee** [comment]
I have been working on the plugin a lot and you may have used a faulty version.  Currently it updates status correctly.
You can change the time between reading status in the code. It is currently set at 10s.  You can also remove the whole section that does the status reading. In my current version it is between lines 549-634.

**Comment by e-mcgee** [comment]
I have implemented new code for the Garage door opener that controls the PGMs and is much happier with it.  It still needs some work to consistently update the final door status but it is much more responsive.

**Comment by e-mcgee** [comment]
I have a new version that works very well.  It requires the latest version of homebridge (v0.4.36) as the previous version I used had a bug.

**Comment by HajLender** [comment]
e-mcgee, sorry I was not folowing the thread. However I want to thank you very much for the great upgrade of the plugin. Now the garage door works perfectly. The initial status is always correctly recognised and the response is really fast - instant.

Only issue I have, that I am not able to directly disarm the alarm from the armed status (writes disarming... but the alarm does not disarm). I am able to put it in home/night mode, but not directly to disarm. From home/night mode I am able to switch to disarm.

I would like to ask you also couple other things:
1. Is there a way to increase the frequency of getting status of specific sensors/zones? I would like some of them to use for light turn on/off (e.g. when motion in garage turn on the light) and by now it works cca. once of five tries (when the status is requested exactly at the time when the motion is detected)

2. I understand I am not using the alarm fully correctly, as I have not specified home/stay status (always using disarm when home). In addition  my night/sleep setting is programmed to home/stay (it means when I go sleep I switch to home/stay). Of course when I switch to night/sleep nothing happens (as it is not programmed). So the two buttons are mixed up. Is there any way I can change them in the plugin instead of calling the technician to reprogram the alarm?

Thank you again for your effort, I really appreciate it
