### ISSUE TITLE
Lights Addition

### ISSUE THREAD

**Issue by deon-wentzel** [e-mcgee/paradox_platform#13]
Hi, 

I have setup, the Alarm and Motion Sensors and all is working thus far, I have Flood Lights configured on PGM, so when the alarm is set off the flood light are switch on for 10 minutes. Do you have any intentions to add light to the plugin via a PGM?

**Comment by e-mcgee** [comment]
Hu Deon,

not at this stage.  I use Sonoff Wifi switches that has their own plugin for homebridge that works very well.  They have built in MQTT support and can be automated with Node Red.  I am rather thinking to include an MQTT support for my plugin to publish status and receive commands. This already exists in TertiusH and other plugins which will make your automation easy.  I found Node Red in particular very powerful and stable. Thus by adding MQTT support it would add great flexibility for integration and automation.  You can do similar automations with HomeKit but i found these to be less stable and reliable.

**Comment by deon-wentzel** [comment]
Thanks for the update, I am using the Sonoff for lights and Fans, but the relay on the Paradox switches on the light when the alarm is triggered.
