### ISSUE TITLE
increasing status frequency

### ISSUE THREAD

**Issue by HajLender** [e-mcgee/paradox_platform#15]
Hi, thank you for your effort, the plugin works much much better now.

Is there a way to increase the frequency of getting status of specific sensors/zones? I would like to use some of them for light turn on/off (e.g. when motion identified in garage turn on the light) and by now it works cca. once of five tries (when the status is requested exactly at the time when the motion is detected)

Thank you

**Comment by e-mcgee** [comment]
I changed the last version to 5 seconds.  There is a constant in the plugin you change.  The minimum would be about three quarters of a second as that is the time it takes to get the status form the alarm. The constant is called POLL_DELAY on line 76 of index.js

**Comment by e-mcgee** [comment]
I just published an updated verison (254) where you can tune all the parameters.  The Poll delay parameter as well so you can do this in your config.json file.
