### ISSUE TITLE
mixed up mode buttons

### ISSUE THREAD

**Issue by HajLender** [e-mcgee/paradox_platform#16]
Hi

I understand my alarm is not programmed correctly.

My alarm technician programmed the night/sleep mode to the home/stay button (so when I go to bed, I turn on home/stay).
I have no program for being home (supposed to be the home/stay button), I use the disarm function when I am at home. 
Is there any way I can change the code in the plugin the way that when I push sleep/night on the homekit app it would launch the home/stay mode programmed in the alarm?

It would be maybe easier then call the technician to reprogram the alarm...

One more thing, If armed It is not possible to directly disarm the alarm from homekit. It shows disarming... but nothing happens with the alarm. I can disarm the alarm from armed mode by switching on homekit to stay/home or night/sleep and then switching disarm.

**Comment by e-mcgee** [comment]
Hi,  the plugin would put the alarm in the correct mode but it cannot change anything on the buttons or keypad as it talks to the alarm via the IP module only.  
You can program the alarm yourself with the Babyware app.  Very easy and worthwhile to get going. Runs on Windows only though.

**Comment by HajLender** [comment]
Unfortunately I am not able to access the alarm via Babyware, as I have no password for it.
I will try to swap the stay and night mode in your code and see if it works. Hopefully not messing it up totally :) 

Thank you again for all your effort. The status reading now works perfectly and I am able to turn on the light with the alarm sensor

**Comment by e-mcgee** [comment]
Hi, I suggest you contact installer and get password.  You will be well advised to configure your own alarm.
I do not think what you suggest will work as the plugin does not change the alarm behaviour but simply provide a way to control it. Your alarm configuration is not altered.
