### ISSUE TITLE
Zone open - crashes homebridge

### ISSUE THREAD

**Issue by vsidlu** [e-mcgee/paradox_platform#17]
Hi,

Everything seems to work - arms - disarms, but when any motion sensor is triggered I get this - 

[2/14/2018, 6:56:20 PM] [Paradox] Zone open
Unhandled Error Detected :  TypeError: Cannot read property 'name' of null
    at _parsestatus (/usr/lib/node_modules/homebridge-paradox-securitysystem/index.js:498:71)
    at Socket.client.on (/usr/lib/node_modules/homebridge-paradox-securitysystem/index.js:1695:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
Restarting homebridge due to an error
restarting...

What do I do wrong? Help needed!

I have Spectrum 6000 and IP150S with v1.40 - i downgraded to v1.39 - still same issue.

**Comment by vsidlu** [comment]
**I solved my problem! Was lucky discovering that zones on keypad are different from zones in mqtt messages. after adding correct zone nr. in config.json - everything is working like charm! if zone is not in config.json you get error!**

**now I have different problem -** 

ERROR LOADING PLUGIN homebridge-paradox-securitysystem:
Error: Plugin /usr/lib/node_modules/homebridge-paradox-securitysystem requires a HomeBridge version of >=0.4.36 which does not satisfy the current HomeBridge version of  0.4.33. You may need to upgrade your installation of HomeBridge.

**i have latest 0.4.38**

**and second error**

throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Error: The requested platform 'Paradox' was not registered by any plugin.

**but everything is working with - sudo homebride -U ~/.homebridge.
will search for solution.**

**Comment by e-mcgee** [comment]
Hi,

just check if you installed homebridge globally (with -g switch) and locally. You may have a different version in either hence why the dependency check fails.  You must install 0.4.36 or later as earlier versions are buggy and do not report status back to HomeKit properly.  I have not tested with 0.4.38.  Your first error may also be the cause of your second error as he plugin did not load and hence the. platform cannot register.

**Comment by vsidlu** [comment]
Hi,

yep! problem is with two homebridge's - one in /usr/lib/node_modules and old in ~/node_modules
will search how to fix it. thanks for great plugin!
