### ISSUE TITLE
Siri and PGM

### ISSUE THREAD

**Issue by deon-wentzel** [e-mcgee/paradox_platform#19]
Hi

I have picked up one minor issue with regards to Siri and the PGMs. If I say to Siri "Open my Garage", the garage opens but Siri responds back saying there was no response received, after a few seconds. I have three PGMs and they all do it..

**Comment by e-mcgee** [comment]
Hi Deon,

yes I noticed as well.  It seems as if there is a timeout issue between homebridge/HomeKit and Siri.  The status values are updated correctly locally to HomeKit however, so I suspect this is something we will have to live with and possibly report on homebridge.

**Comment by deon-wentzel** [comment]
Have you tested the latest Homebridge?

**Comment by e-mcgee** [comment]
No. I am still on 0.4.36. I think the latest is 0.4.38.

**Comment by deon-wentzel** [comment]
Thanks!!!
