### ISSUE TITLE
Homebridge Version

### ISSUE THREAD

**Issue by deon-wentzel** [e-mcgee/paradox_platform#24]
Hi

Are you still using Homebridge 0.4.36 or have you upgraded? The latest is Homebridge 0.4.42 have you tested this version?

**Comment by e-mcgee** [comment]
Still using old version

**Comment by deon-wentzel** [comment]
Thanks

**Comment by e-mcgee** [comment]
HI Deon,

updated to homebridge 0.4.44 and plugin still works fine.

**Comment by deon-wentzel** [comment]
Will  do thanks

**Comment by deon-wentzel** [comment]
Hi,

I have been running home bridge 0.4.44 and if find it unstable, so far twice I  had to disconnect and reconnect, because the PGMs (the gate and the garage door) would not open or close, and the same applied to the remotes. Once I used the connect in home app to disable and enable it starts working again.

**Comment by deon-wentzel** [comment]
All is working fine now...
