### ISSUE TITLE
IP150 4.20.008 version

### ISSUE THREAD

**Issue by erokoder** [e-mcgee/paradox_platform#27]
Hello,

first off all thanks for this plugin.
1. I bought IP150 before few days on version 4.2 and I use app Inside GOLD from paradox.
So, I assume that I must downgrade version  4.2 to lower. That is temporary or new version never be supported by this and similar plugin? 
2. Also, there is some way to use a serial port instead IP150? 
3. This plugin supports the SP7000?
4. Some good tutorial for downgrade my IP150?

Thanks

**Comment by iondarie** [comment]
Hello,

1. The newer version will most likely never be supported (to many people tried to make it work without any luck )
2. I personally tried everything i could find to make it work by serial and i had no luck
3. I use a SP7000, it works flawless except for home automation if u have 2 partitions
4.  https://github.com/Tertiush/ParadoxIP150v2/issues/22 search for posts of nezmogus (a router wich supports DD-WRT would be ideal)

**Comment by erokoder** [comment]
Hello @iondarie, 
I success install to ma sp7000, and work excelent. 
I dont use partition 2, so can I remove it on config file, or to another way? 
Also How can Set notification with custom Alarm sound when Sistem Armed AND somebody get on House?
Can I use iparadox application im same time with homebridge?
Thanks

**Comment by iondarie** [comment]
Hi @erokoder,

1. Simply mark secon partition as inactive look at config.sample.json

      {
        		"name": "Alarm_Partition_2|inactive",
        		"config": {
        			"type": "Alarm",
                                "partition": 1,
                                "topic": "Paradox/partition2/"
        			}
        	 	},

2. Homebridge/homekit does not allow any sound customization

3. Yes you can you simmply turn the connected switch to off

For more detailed info please read the wiki.

**Comment by erokoder** [comment]
@iondarie 
1. I found it, thanks.
2. I get notification when system arm or disarmed. But when alarm turn on, I don't receive any information. Maybe I mistake in something. 
3. Yes, but I use Motion detector for turn on light in some hallway, and some other thing. So I need constantly connect. So, there is no way to connect to iparadox and homebridge  in same time?

**Comment by e-mcgee** [comment]
Hi,
no.  The IP module only allows one login. You can disconnect the alarm switch control to disable the plugin and then login with iParadox, work with iParadox and then reconnect the plugin, but they cannot work together at the same time.

**Comment by erokoder** [comment]
@e-mcgee 
Do you receive notification when alarm trigger by somebody?

**Comment by e-mcgee** [comment]
No, I have picked up the same issue.  I need to modify the code to better pick up the alarm triggering when I have a chance.

**Comment by erokoder** [comment]
@e-mcgee 
That is be good to fix it. Because now I don't know when somebody trigger alarm. Becouse of that I ask for together work iparadox and homebridge.
Also maybe in this plugin you can find some useful homebridge-paradox-security-system
Greate plugin, thank a lot for shere with us.

**Comment by deon-wentzel** [comment]
HI, I have been using the App, House Alarm, it notifies me thru Apple's notification if the Alarm is triggered, with the Plug-in enabled. The IP150 can be configured to send emails on Alarms, the House Alarm APP changes this setting to use Apple Notification.

**Comment by erokoder** [comment]
@deon-wentzel 
Hi, 
I also use that app House Alarm. But when you connect to ip150 over homebridge, you can’t use that app Because You can’t login. Or?
I know that I can configure e-mail, but that si not pretty usfule, I will Wait fix anc help with that fix.
 We can Open new issue for that, somebody meybi Resolve this.

**Comment by deon-wentzel** [comment]
You are correct, you cannot use the House Alarm APP to login, but with the Notification you do not need to login, it tells you which zone has been triggered.

I agree, a fix would be preferable.

**Comment by erokoder** [comment]
@deon-wentzel
Intersting, I will try tonight.

**Comment by deon-wentzel** [comment]
So at the office I have two partitions, with the notification I can check to see if both partitions are active when using the Automation, like turning there Alarm to Away on both Partitions, turning all the lights and air conditioners, off. When doing this sometimes the 2nd Partition does not change, with the Notifications it will only notify on the partition that has changed

**Comment by iondarie** [comment]
@deon-wentzel how did you manage to get automation working with 2 partitions?

Mine only arms/disams one partition...

I have an SP7000

**Comment by deon-wentzel** [comment]
See my config below, I have a MG5050

                             {
					"name": "Alarm_Partition_1",
					"config": {
						"type": "Alarm",
						"partition": 0,
						"topic": "Paradox/partition1/"
					}
				},
				{
					"name": "Alarm_Partition_2",
					"config": {
						"type": "Alarm",
						"partition": 1,
						"topic": "Paradox/partition2/"
					}
				},

**Comment by iondarie** [comment]
I have the exact config... maybe a problem with timing

**Comment by deon-wentzel** [comment]
When I use automation to arm and disarm, there is a 60% chance both  arm or disarm, 40% of the time I have do the 2nd one manually

**Comment by deon-wentzel** [comment]
House Alarm will tell me if the 2nd one does not arm...

**Comment by erokoder** [comment]
@e-mcgee @deon-wentzel @iondarie 
I confirm that HOUSE ALARM APP notification working without login. So for notification use House Alarm app, for arm/disarm Home APP. 
I hope to fast fix 

Maybe some of you know How I can make zone on paradox only for report status. Not for Full Arm.
I want connect Garage Door Magnet reed sensor to one of my free zone. And check that state OPEN or CLOSE?

**Comment by deon-wentzel** [comment]
Hi, I have a PGM with a Contact Sensor on its own zone in my garage. If I look at the Home APP I can see if the garage is open or close.  If I open the garage door I get a notification the garage door is open and the same when the garage door is close.

**Comment by erokoder** [comment]
@deon-wentzel 
Wiring: One wire in PGM1OUT, Another in Earth or? I have SP7000.
Also What is set for  ACTIVATE/DEACTIVATE Even , tEventGroup and SubGroup when programin pgm?

**Comment by deon-wentzel** [comment]
Two wireless PGM, one for the motor and one for the contact Sensor. Each have their own zones.
