### ISSUE TITLE
Home automation with 2 partitions

### ISSUE THREAD

**Issue by iondarie** [e-mcgee/paradox_platform#28]
I have a SP7000 with 2 partitions, when i leave home it only arms one partition, upon returning home it disarms only one partition 

Sometimes it works PERFECT but most of the time it will only arm/disarm 1 partition. I tried to increase delaybetweencmds but it seems it has no effect.

Is there something that can be done to fix this?

Thank you

**Comment by e-mcgee** [comment]
I am not sure if I follow you correctly but remember that the two partitions are presented as two separate alarms.  So you have to arm each separately.  Are you saying that you arm both and then only one actually arms?
