### ISSUE TITLE
Not able to arm/disarm

### ISSUE THREAD

**Issue by pplevesque** [e-mcgee/paradox_platform#29]
Hi,

Thank you very much for your work.

I'm able to get the module to communicate with the homebridge, status is updated but I cannot control the arm/disarm from the phone. When I ask for Arm on the phone, homebridge logs says Controlling but nothing happens on the panel.

When logging in the web interface of the IP150, I must enter Panel User Code and IP Password.

Is it something I'm missing?

Type | SP5500
Firmware version | 4.78

IP150
Firmware version | 1.34.00
Hardware | 020
ECO | N009
IP boot | 2.12

Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] Controlling Alarm State...
Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] Message received
Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] message length =
Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] 53
Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] Checksum OK
Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] Message received
Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] message length =
Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] 53
Oct 26 00:21:39 localhost homebridge: [10/26/2018, 12:21:39 AM] [Paradox] Checksum OK
Oct 26 00:21:40 localhost homebridge: [10/26/2018, 12:21:40 AM] [Paradox] Statusses:
Oct 26 00:21:40 localhost homebridge: [10/26/2018, 12:21:40 AM] [Paradox] Area 1 - [object Object]
Oct 26 00:21:40 localhost homebridge: [10/26/2018, 12:21:40 AM] [Paradox] Area 2 - [object Object]
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Mute : [false]
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Geting Status...
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Got status
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Results:
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Zone 1 off (Smoke)
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Zone 2 off (Water)
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Zone 3 off (Living Room)
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Zone 4 off (Basement)
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Zone 5 off (Back door)
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Zone 6 off (Front door)
Oct 26 00:21:44 localhost homebridge: [10/26/2018, 12:21:44 AM] [Paradox] Alarmstatus :Disarmed

Thanks in advance for your help

**Comment by vsidlu** [comment]
Hi,

Need help to figure out! Sometimes I see objectObject - this mean I do not get info to homekit.
Same as post above!

Oct 26 00:21:40 localhost homebridge: [10/26/2018, 12:21:40 AM] [Paradox] Area 1 - [**object Object]**
Oct 26 00:21:40 localhost homebridge: [10/26/2018, 12:21:40 AM] [Paradox] Area 2 - **[object Object]**

**Comment by e-mcgee** [comment]
It does look like there is something wrong with your partition configurations,  Can you send me your config.json file.  Just delete your sensitive info before posting.

**Comment by vsidlu** [comment]
its working ok after homebridge restart. i think i have problem with network. thanks for your assistance.

**Comment by pplevesque** [comment]
Hi,

Sorry for long time not update.

I figured that if a PC Password is set on the IP150, the plugin is unable to pass commands to arm or disarm. I called the security system installer and asked him for PC Password removal and all started to work.
