### ISSUE TITLE
Alarm Status

### ISSUE THREAD

**Issue by agisofttm** [e-mcgee/paradox_platform#7]
I'm Fascinated about this working and simple implementation code, but is there a way to describe a time to connect to IP150 module? Not every 2-3 seconds.... I have an issue, when I restart homebridge, every time my alarm status showing Updating, till a disarm, or arm it.... after this everything working perfectly.

**Comment by e-mcgee** [comment]
Hi,
yes the initial status is still a problem I have not solved.  The same is true for PGM's but once the PGMs are triggered for the first time they get to the correct state, as with the alarm state.  I will see if I can improve the initial state at all.
I talk to the alarm every 10 seconds.  This is hard coded in line 648 (v48) if you want to change it.  Bear in mind that it takes over 4 seconds to log into the alarm and read the status.  I tried to reduce this but it just causes the communication to fail if I make the time shorter.  After this it "rests" for just under 6 seconds and repeats the process.

**Comment by cybertza** [comment]
What i have done is with nodeR create an inter-mediate topic that i parse, and then save as Persistant, this causes as per the operation of MQTT.p that the last state gets pushed to the newly connected client.

https://community.home-assistant.io/t/home-assistant-and-paradox-alarm-panels/16042/8
for reference, Personally i know the winload app does know what state the alarm is in when it connects, so i know its do able.

**Comment by e-mcgee** [comment]
Hi,

I have now implemented completely different GarageDoorOpener code based on another Raspberry Pi Garage door opener plugin that works pretty well. it is now able to initialise the state correctly on startup.  The update of the state of the garage door is still not completely consistent but overall I am much happier with the Garage door opener code.

**Comment by e-mcgee** [comment]
The door state now updates consistently.  It was a bug in homebridge version I used.  Update homebridge to v 0.4.36 and use my latest release (v0.196)
