### ISSUE TITLE
Assigning partitions

### ISSUE THREAD

**Issue by jclendon** [e-mcgee/paradox_platform#8]
Hi,
Fantastic plugin! I have it working with my Paradox SP5500 with IP150. I have 2 partitions in my setup so it would be great if you could create more than one alarm instance with a partition variable in the config.json file so that you can you can control each partition individually.
Thanks!

**Comment by e-mcgee** [comment]
Hi,

Thanks for feedback.
This is the second request for multiple partition.  I will try to add as soon as I have time.

**Comment by deon-wentzel** [comment]
I see in the index.js you have two partitions?  What do we need to add in the config.json to recognize the 2nd partition?

if (partition == 0) {
            switch (state) {
                case "ARM" :
                    message1 = CONTROLALARM_ARM_P0_MSG;
                    break;
                case "DISARM" :
                    message1 = CONTROLALARM_DISARM_P0_MSG;
                    break;
                case "SLEEP" :
                    message1 = CONTROLALARM_SLEEP_P0_MSG;
                    break;
                case "STAY" :
                    message1 = CONTROLALARM_STAY_P0_MSG;
                    break;
            }
        }
        if (partition == 1) {
            switch (state) {
                case "ARM" :
                    message1 = CONTROLALARM_ARM_P1_MSG;
                    break;
                case "DISARM" :
                    message1 = CONTROLALARM_DISARM_P1_MSG;
                    break;
                case "SLEEP" :
                    message1 = CONTROLALARM_SLEEP_P1_MSG;
                    break;
                case "STAY" :
                    message1 = CONTROLALARM_STAY_P1_MSG;
                    break;
            }
        }

**Comment by e-mcgee** [comment]
At the moment the second partition is not yet implemented. In the code I have simply made provision for the different messages to send to the alarm.  I need to add code to recognise the config of multiple partitions and also change the data structures to accommodate this.

**Comment by e-mcgee** [comment]
2 partitions now supported.

**Comment by deon-wentzel** [comment]
Hi,

Installed it and working great with both partitions, will keep you posted if I find any issues.

**Comment by e-mcgee** [comment]
Thanks
