### ISSUE TITLE
Paradox not updating status

### ISSUE THREAD

**Issue by sgsteyn** [e-mcgee/paradox_platform#9]
Not sure what I am doing wrong but having similar problem with your plugin and the original using Tertius scripts. With your plugin I am able to get it up running and with cycling trough different arming states I manage to get armed\disarmed working trough the Home app and even PGM. But zone states are never updated and also if I change the alarm outside of Home app, it doesn't get updated either. 

Any assistance would be appreciated. This is my first experimentation on the platform.

This is what I currently have in config.json. Removed all other zones for troubleshooting
{
			"platform": "Paradox",
			"ip": "192.168.XXXXX",
			"port": 10000,
			"password": "XXXXX",
			"accessories": [{
					"name": "Alarm",
					"config": {
						"type": "Alarm"
					}
				},

				{
					"name": "Gate",
					"config": {
						"type": "Garage Door",
                        "zone" : 1,
						"pgm": 3
					}
				}
			]
		}

**Comment by e-mcgee** [comment]
Hi,

to debug I suggest you run homebridge from the command line and should then be able to see the console output messages. That way you should see the zone status messages and also the alarm status.
It could be that your zone numbers are out by one and hence you are reading the wrong status messages.  By looking at the debug messages you should see the status and can then trigger zones to see if they update.
Let me know what you see.

**Comment by sgsteyn** [comment]
Hi,
I have now discovered that my alarm and IP module firmware was out of date and decided to upgrade all to the latest, not realizing that IP150 v4 is a completely different ball game. Not sure if you have tested with it and if it will work? I am trying to see if I can find a way to downgrade.

At the moment I get an error just saying "Error Logging In". Is there anyway to get more detailed output or should I assume there is nothing more to the error than my credentials are not being accepted?

Something also worth mentioning (from reading other issues), I also have 2x Partitions. I am only trying to control/monitor the one but not sure how it will affect the plugin?

Thank you for assistance!

**Comment by e-mcgee** [comment]
Hi,
unfortunately I have the IP100 module still so cannot test IP150v4.

You can get more detailed debug by using the log command.  Basically you are not getting the correct response code in line 196 of my current version (r129).  You can simply log the output in the login function to try and get more detail on the response codes.

On the 2 partitions, the code is ready for supporting that. I already had two requests from other users.  My biggest issue is going to be how the multiple partitions will influence the response codes and as I only have one partition I am not able to test so at this stage is still a bit hesitant to attempt the multiple partition implementation.

**Comment by deon-wentzel** [comment]
If you need help with the response codes for multiple partitions, let me know what I need todo

**Comment by e-mcgee** [comment]
Hi Deon,
I have published v130 that outputs the received messages from the alarm to the console.  If you could send me your console output with different alarm states on both partitions I could try to identify where the different partition status info is stored.

**Comment by deon-wentzel** [comment]
Hi, sorry for the delay, so I will install v130 this weekend and send you the result.

**Comment by e-mcgee** [comment]
Hi
I have a new release that updates the status values correctly from startup and when any changes happen.  There was a bug in the homebridge version I used. After updating to the latest all works well now.  Homebridge now needs to be at v0.4.36 or higher.

**Comment by e-mcgee** [comment]
2 partitions now supported
